name: roome
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider:
  intl:
  percent_indicator:
  image_picker: 
  connectivity:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/bangladesh.jpg
    - assets/images/bd.jpg
    - assets/images/p1.jpg
    - assets/images/p2.jpg
    - assets/images/p3.jpg
    - assets/images/p4.jpg
    - assets/images/p5.jpg
    - assets/images/no_net.jpg
    - assets/images/l1.jpg
    - assets/images/l2.jpg
    - assets/images/l3.jpg
    - assets/images/voucher.jpg
    - assets/images/logo.png
    - assets/images/fb.png
    - assets/images/google.png
    - assets/images/capetown.jpg
    - assets/images/japan.jpg
    - assets/images/russia.jpg
    - assets/images/thailand.jpg
    - assets/images/hotel.jpg
    - assets/images/house.jpg
    - assets/images/h1.jpg
    - assets/images/h2.jpg
    - assets/images/h3.jpg
    - assets/images/h4.jpg
    - assets/images/man.png
    - assets/images/man1.png
    - assets/images/man2.jpg
    - assets/images/man2.png
    - assets/images/man3.png
    - assets/images/refer.jpg
    - assets/images/qrcode.png
    - assets/images/coupons.jpg
    - assets/images/boat.jpg
    - assets/images/login.jpg
    - assets/images/register.jpg
    - assets/images/avatar.png
    - assets/images/user.png
    - assets/images/no_net.png
    - assets/images/deluxe.jpg
    - assets/images/premium.jpeg
    - assets/images/super.jpg
    - assets/images/suite.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Bold.ttf
          weight: 900
        - asset: fonts/BebasNeue-Book.ttf
        - asset: fonts/BebasNeue-Light.ttf
          weight: 300
        - asset: fonts/BebasNeue-Regular.ttf
          weight: 400
        - asset: fonts/BebasNeue-Thin.ttf
          weight: 200
          style: italic
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
          weight: 900
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-Hairline.ttf
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-Regular.ttf
          weight: 400
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Bold.ttf
          weight: 700
        - asset: assets/fonts/Oswald/Oswald-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Oswald/Oswald-Light.ttf
          weight: 300
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
          weight: 400
    - family: Open Sans Condensed
      fonts:
        - asset: assets/fonts/Open_Sans_Condensed/OpenSansCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Open_Sans_Condensed/OpenSansCondensed-Light.ttf
          weight: 300
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
